#include "cpu.h"

using opcode_handler = void (Cpu::*)();
constexpr int NUM_OPCODES = 512;

static constexpr opcode_handler opcode_table[NUM_OPCODES] = {
/*00, NOP*/         &Cpu::noop,
/*01, LD BC, n16*/  &Cpu::ld_imm16_to_reg16,
/*02, LD [BC] A*/   &Cpu::ld_acc_to_memory,
/*03, INC BC*/      &Cpu::step16_handler,
/*04, INC B*/       &Cpu::step8_handler,
/*05, DEC B*/       &Cpu::step8_handler,
/*06, LD B, n8*/    &Cpu::ld_imm8_to_dest8,
/*07, RLCA*/        &Cpu::rotate_left_handler,
/*08, LD [a16] SP*/ &Cpu::ld_sp_to_mem,
/*09, ADD HL BC*/   &Cpu::add_hl_handler,
/*0a, LD A [BC]*/   &Cpu::ld_mem8_to_acc,
/*0b, DEC BC*/      &Cpu::step16_handler,
/*0c, INC C*/       &Cpu::step8_handler,
/*0d, DEC C*/       &Cpu::step8_handler,
/*0e, LD C, n8*/    &Cpu::ld_imm8_to_dest8,
/*0f, RRCA*/        &Cpu::rotate_right_handler,
/*10, NOP*/         &Cpu::stop,
/*11, LD DE, d16*/  &Cpu::ld_imm16_to_reg16,
/*12, LD [DE] A*/   &Cpu::ld_acc_to_memory,
/*13, INC DE*/      &Cpu::step16_handler,
/*14, INC D*/       &Cpu::step8_handler,
/*15, DEC D*/       &Cpu::step8_handler,
/*16, LD D, n8*/    &Cpu::ld_imm8_to_dest8,
/*17, RLA*/         &Cpu::rotate_left_handler,
/*18, JR e8*/       &Cpu::jr,
/*19, ADD HL DE*/   &Cpu::add_hl_handler,
/*1a, LD A [DE]*/   &Cpu::ld_mem8_to_acc,
/*1b, DEC DE*/      &Cpu::step16_handler,
/*1c, INC E*/       &Cpu::step8_handler,
/*1d, DEC E*/       &Cpu::step8_handler,
/*1e, LD E, n8*/    &Cpu::ld_imm8_to_dest8,
/*1f, RRA*/         &Cpu::rotate_right_handler,
/*20, JR NZ, e8*/   &Cpu::jr,
/*21, LD HL, d16*/  &Cpu::ld_imm16_to_reg16,
/*22, LD [HL] A*/   &Cpu::ld_acc_to_memory,
/*23, INC HL*/      &Cpu::step16_handler,
/*24, INC H*/       &Cpu::step8_handler,
/*25, DEC H*/       &Cpu::step8_handler,
/*26, LD H, n8*/    &Cpu::ld_imm8_to_dest8,
/*27, DAA*/         &Cpu::daa_handler,
/*28, JR Z, e8*/    &Cpu::jr,
/*29, ADD HL HL*/   &Cpu::add_hl_handler,
/*2a, LD A [HL+]*/  &Cpu::ld_mem8_to_acc,
/*2b, DEC HL*/      &Cpu::step16_handler,
/*2c, INC :*/       &Cpu::step8_handler,
/*2d, DEC :*/       &Cpu::step8_handler,
/*2e, LD L, n8*/    &Cpu::ld_imm8_to_dest8,
/*2f, RRA*/         &Cpu::complement_acc,
/*30, JR NC, e8*/   &Cpu::jr,
/*31, LD SP, d16*/  &Cpu::ld_imm16_to_reg16,
/*32, LD [HL-] A*/  &Cpu::ld_acc_to_memory,
/*33, INC SP*/      &Cpu::step16_handler,
/*34, INC [HL]*/    &Cpu::step8_handler,
/*35, DEC [HL]*/    &Cpu::step8_handler,
/*36, LD [HL], n8*/ &Cpu::ld_imm8_to_dest8,
/*37, SCF*/         &Cpu::set_carry_flag,
/*38, JR C, e8*/    &Cpu::jr,
/*39, ADD HL SP*/   &Cpu::add_hl_handler,
/*3a, LD A [HL-]*/  &Cpu::ld_mem8_to_acc,
/*3b, DEC SP*/      &Cpu::step16_handler,
/*3c, INC A*/       &Cpu::step8_handler,
/*3d, DEC A*/       &Cpu::step8_handler,
/*3e, LD A, n8*/    &Cpu::ld_imm8_to_dest8,
/*3f, RRA*/         &Cpu::complement_carry_flag,
/*40, */            &Cpu::ld_reg_or_memref_to_dest8,
/*41, */            &Cpu::ld_reg_or_memref_to_dest8,
/*42, */            &Cpu::ld_reg_or_memref_to_dest8,
/*43, */            &Cpu::ld_reg_or_memref_to_dest8,
/*44, */            &Cpu::ld_reg_or_memref_to_dest8,
/*45, */            &Cpu::ld_reg_or_memref_to_dest8,
/*46, */            &Cpu::ld_reg_or_memref_to_dest8,
/*47, */            &Cpu::ld_reg_or_memref_to_dest8,
/*48, */            &Cpu::ld_reg_or_memref_to_dest8,
/*49, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4a, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4b, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4c, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4d, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4e, */            &Cpu::ld_reg_or_memref_to_dest8,
/*4f, */            &Cpu::ld_reg_or_memref_to_dest8,
/*50, */            &Cpu::ld_reg_or_memref_to_dest8,
/*51, */            &Cpu::ld_reg_or_memref_to_dest8,
/*52, */            &Cpu::ld_reg_or_memref_to_dest8,
/*53, */            &Cpu::ld_reg_or_memref_to_dest8,
/*54, */            &Cpu::ld_reg_or_memref_to_dest8,
/*55, */            &Cpu::ld_reg_or_memref_to_dest8,
/*56, */            &Cpu::ld_reg_or_memref_to_dest8,
/*57, */            &Cpu::ld_reg_or_memref_to_dest8,
/*58, */            &Cpu::ld_reg_or_memref_to_dest8,
/*59, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5a, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5b, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5c, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5d, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5e, */            &Cpu::ld_reg_or_memref_to_dest8,
/*5f, */            &Cpu::ld_reg_or_memref_to_dest8,
/*60, */            &Cpu::ld_reg_or_memref_to_dest8,
/*61, */            &Cpu::ld_reg_or_memref_to_dest8,
/*62, */            &Cpu::ld_reg_or_memref_to_dest8,
/*63, */            &Cpu::ld_reg_or_memref_to_dest8,
/*64, */            &Cpu::ld_reg_or_memref_to_dest8,
/*65, */            &Cpu::ld_reg_or_memref_to_dest8,
/*66, */            &Cpu::ld_reg_or_memref_to_dest8,
/*67, */            &Cpu::ld_reg_or_memref_to_dest8,
/*68, */            &Cpu::ld_reg_or_memref_to_dest8,
/*69, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6a, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6b, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6c, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6d, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6e, */            &Cpu::ld_reg_or_memref_to_dest8,
/*6f, */            &Cpu::ld_reg_or_memref_to_dest8,
/*70, */            &Cpu::ld_reg_or_memref_to_dest8,
/*71, */            &Cpu::ld_reg_or_memref_to_dest8,
/*72, */            &Cpu::ld_reg_or_memref_to_dest8,
/*73, */            &Cpu::ld_reg_or_memref_to_dest8,
/*74, */            &Cpu::ld_reg_or_memref_to_dest8,
/*75, */            &Cpu::ld_reg_or_memref_to_dest8,
/*76, */            &Cpu::halt,
/*77, */            &Cpu::ld_reg_or_memref_to_dest8,
/*78, */            &Cpu::ld_reg_or_memref_to_dest8,
/*79, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7a, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7b, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7c, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7d, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7e, */            &Cpu::ld_reg_or_memref_to_dest8,
/*7f, */            &Cpu::ld_reg_or_memref_to_dest8,
};  